### ISSUE TITLE
Shared public sage for all boards

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [milkytiptoe/Name-Sync#53]
https://boards.4chan.org/qa/thread/1380723

The title is the request and there is not much else to say.

**Comment by ErinSteph** [comment]
I can probably answer this one

nah sorry

On 8 Jun 2017, at 3:52 pm, I wish I could change my name <notifications@github.com<mailto:notifications@github.com>> wrote:


https://boards.4chan.org/qa/thread/1380723

The title is the request and there is not much else to say.

**Comment by ididntknowicoulddothatXD** [comment]
Ah, what a pity.

**Comment by nokosage** [comment]
This is kind of already a thing on boards Name Sync is used on, with the `Hide Sage: Share none of your sync fields when sage is in the email field. ` option unchecked; it will show sage in the email field like it used to.

I liked it more when it was visible, too.
