### ISSUE TITLE
sage in E-mail field creates link to mailto:sage

### ISSUE THREAD

**Issue by docrobbins** [milkytiptoe/Name-Sync#54]
"sage" in E-mail field creates link to mailto:sage

**Comment by nokosage** [comment]
Click the "NS" button to go into the options menu, check the box
```Hide Sage: Share none of your sync fields when sage is in the email field.```
and refresh the page. NS will not share any fields, then.

I guess if the other fields need to be displayed, I could change its functionality to only hide sage in the email field.
